# Automatic dependencies update suggestions

version: 2
updates:
  # Enable version updates for maven
  - package-ecosystem: "maven"
    # Look for `pom.xml` in the `root` directory
    directory: "/"
    # Check the maven registry for updates every day (weekdays)
    schedule:
      interval: "daily"